//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoNgocHai_2122110473_ASP.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public int CreatedOnUtc { get; set; }
        public string Address { get; set; }
        public int Status { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
